extends Node

const DROP_SCENE := preload("res://scenes/effects/blood_drop.tscn")
const ENEMY_SCENE := preload("res://scenes/enemy.tscn")
const STAIN_SCENE := preload("res://scenes/blood_stain.tscn")
const BLOOD_SYSTEM_SCRIPT := preload("res://scripts/effects/blood_system.gd")
const CORPSE_SCENE := preload("res://scenes/corpse.tscn")

var failures := 0

func _ready() -> void:
	CleanupRegistry.reset()
	var drop := DROP_SCENE.instantiate() as BloodDrop
	drop.setup(0.8, Vector2.RIGHT, {"spread": 1.35, "darken": 0.2, "cleanup": 3})
	add_child(drop)
	_expect(drop.is_in_group("blood_source"), "fresh floor blood should remain a shoe-contamination source")
	_expect(drop.get_cleanup_cost() == 3, "absorbent surfaces should increase cleanup cost")
	_expect(drop.is_in_group("blood_clue"), "settled droplets should be visible forensic clues")
	var blood_system := Node2D.new()
	blood_system.set_script(BLOOD_SYSTEM_SCRIPT)
	add_child(blood_system)
	blood_system.spawn_micro_drop(Vector2(60, 60), 0.5, Vector2.RIGHT)
	blood_system.spawn_micro_drop(Vector2(61, 60), 0.5, Vector2.RIGHT)
	await get_tree().process_frame
	var pixel_drop_count := int(blood_system.ground_canvas.get_debug_pixel_count())
	_expect(pixel_drop_count > 0 and pixel_drop_count <= 6, "overlapping micro blood should merge into a compact shared pixel canvas")
	_expect(blood_system.ground_canvas.chunks.size() == 1, "nearby droplets should occupy one sparse texture chunk instead of growing the scene tree")
	var wall_stain = STAIN_SCENE.instantiate()
	add_child(wall_stain)
	wall_stain.setup(Vector2.RIGHT, 1.0, true)
	_expect(not wall_stain.is_in_group("blood_clue"), "wall stains must not become unreachable AI investigation targets")
	var scrub_stain = STAIN_SCENE.instantiate()
	add_child(scrub_stain)
	scrub_stain.setup(Vector2.RIGHT, 1.2, false)
	var scrub_progress_before := float(scrub_stain.get_cleanup_progress())
	_expect(scrub_stain.clean_at(scrub_stain.global_position + Vector2(24, 0), 1), "a valid smart stroke near a selected stain must always clean its nearest dirty section")
	_expect(float(scrub_stain.get_cleanup_progress()) > scrub_progress_before, "smart strokes must produce measurable cleanup progress")
	var line_stain = STAIN_SCENE.instantiate()
	add_child(line_stain)
	line_stain.setup(Vector2.RIGHT, 2.8, false, false, "line", 0.2, "puncture")
	for lobe in line_stain.lobes:
		_expect((lobe.position as Vector2).length() <= 24.5, "gunshot line blood must remain a compact broken droplet chain")
	for streak in line_stain.streaks:
		_expect((streak.start as Vector2).distance_to(streak.end as Vector2) <= 6.0, "gunshot blood streak segments must not become long solid rays")
	var residue_stain = STAIN_SCENE.instantiate()
	add_child(residue_stain)
	residue_stain.setup(Vector2.RIGHT, 0.6, false, false, "fan", 0.2, "puncture")
	for cleaning_pass in range(32):
		if residue_stain.is_ultraviolet_residue(): break
		residue_stain.clean_stroke(residue_stain.global_position, Vector2.RIGHT, 8, "mop")
	_expect(residue_stain.is_ultraviolet_residue(), "ordinary mopping should leave a non-blocking ultraviolet forensic trace")
	residue_stain.set_ultraviolet_visible(true)
	_expect(residue_stain.ultraviolet_visible, "UV illumination should reveal cleaned biological residue")
	var shotgun := AttackCatalog.get_gun_data("shotgun")
	_expect(shotgun.pellet_count == 7, "shotgun should emit seven pellets")
	_expect(shotgun.blood_pattern == "radial", "shotgun should use radial blood geometry")
	_expect(shotgun.hearing_radius >= 600.0, "shotgun should alert most of a floor")
	var pistol_context := DamageContext.create(Vector2(10, 10), Vector2.RIGHT, 1, "pistol", 20.0, true, "torso")
	var shotgun_context := DamageContext.create(Vector2(10, 10), Vector2.RIGHT, 1, "shotgun", 20.0, true, "head")
	_expect(shotgun_context.energy > pistol_context.energy, "DamageContext should preserve weapon energy differences for shared impact feedback")
	_expect(shotgun_context.hit_zone == "head" and shotgun_context.lethal, "DamageContext should preserve hit-zone and lethal facts")
	var pistol_violence := AttackCatalog.get_violence_profile("pistol")
	var shotgun_violence := AttackCatalog.get_violence_profile("shotgun")
	var knife_violence := AttackCatalog.get_violence_profile("knife")
	_expect(str(pistol_violence.wound) == "puncture", "pistol trauma should preserve a narrow puncture identity")
	_expect(str(shotgun_violence.wound) == "blast" and int(shotgun_violence.limbs) > 0, "shotgun trauma should support blast wounds and modular dismemberment")
	_expect(str(knife_violence.wound) == "slash", "knife trauma should preserve a directional slash identity")
	_expect(shotgun_context.violence_profile == shotgun_violence, "DamageContext should carry the shared violence profile without re-deriving it downstream")
	blood_system.emit_context(shotgun_context)
	_expect(blood_system.violence_scale == 1.0, "blood intensity scaling should remain an explicit run modifier")
	var enemy := ENEMY_SCENE.instantiate()
	add_child(enemy)
	var first_regions: Dictionary = enemy._get_blood_clue_regions()
	var clue_region := Vector2i(floori(drop.global_position.x / 24.0), floori(drop.global_position.y / 24.0))
	var first_generation := int((first_regions.get(clue_region, {}) as Dictionary).get("generation", 0))
	var later_drop := DROP_SCENE.instantiate() as BloodDrop
	later_drop.position = drop.position + Vector2(2, 0)
	add_child(later_drop)
	enemy.blood_clue_cache_bucket = -1
	var refreshed_regions: Dictionary = enemy._get_blood_clue_regions()
	_expect(int((refreshed_regions.get(clue_region, {}) as Dictionary).get("generation", 0)) > first_generation, "new blood in an investigated region must advance its forensic generation")
	_expect(enemy.classify_hit_zone(enemy.to_global(Vector2(4, 0))) == "head", "forward local impacts should classify as head hits")
	_expect(enemy.classify_hit_zone(enemy.to_global(Vector2(0, 0))) == "torso", "central impacts should classify as torso hits")
	_expect(enemy.classify_hit_zone(enemy.to_global(Vector2(-5, 0))) == "limb", "rear local impacts should classify as limb hits")
	var corpse = CORPSE_SCENE.instantiate()
	add_child(corpse)
	_expect(corpse.z_index >= 4, "corpse anatomy must render above pools, drops, footprints, and loose gore")
	corpse.setup(0.0, Vector2.RIGHT, 12.0, 1.7, "firearm_torn", "head", "shotgun")
	_expect(not corpse.has_node("BodySprite"), "compact corpse must not load the retired oversized authored sprite layer")
	_expect(corpse.wound_kind == "blast", "corpse presentation should inherit the lethal weapon wound identity")
	_expect(not corpse.missing_modules.is_empty(), "high-energy shotgun corpses should expose modular body loss")
	_expect(corpse.dismemberment_state == "head_destroyed" and corpse.missing_modules.has("head"), "shotgun head kills must leave an explicitly destroyed-head corpse state")
	var pistol_corpse = CORPSE_SCENE.instantiate()
	add_child(pistol_corpse)
	pistol_corpse.setup(0.0, Vector2.RIGHT, 8.0, 1.0, "firearm", "torso", "pistol")
	_expect(pistol_corpse.dismemberment_state in ["torso_puncture", "shoulder_puncture"] and pistol_corpse.missing_modules.is_empty(), "pistol torso kills should vary wounds while preserving anatomy")
	_expect(pistol_corpse.corpse_pose_variant >= 0 and pistol_corpse.corpse_pose_variant <= 3, "every firearm corpse should select one of four fall poses")
	var cycled_poses: Array[int] = [pistol_corpse.corpse_pose_variant]
	for pose_index in range(3):
		var pose_corpse = CORPSE_SCENE.instantiate()
		add_child(pose_corpse)
		pose_corpse.setup(0.0, Vector2.RIGHT, 8.0, 1.0, "firearm", "torso", "pistol")
		cycled_poses.append(pose_corpse.corpse_pose_variant)
		pose_corpse.queue_free()
	_expect(cycled_poses.duplicate().all(func(pose): return cycled_poses.count(pose) == 1), "four consecutive kills with one gun must cycle through four distinct silhouettes")
	var lmg_corpse = CORPSE_SCENE.instantiate()
	add_child(lmg_corpse)
	lmg_corpse.setup(0.0, Vector2.RIGHT, 24.0, 1.7, "firearm_gib", "limb", "lmg")
	_expect(lmg_corpse.dismemberment_state == "limb_severed" and not lmg_corpse.missing_modules.is_empty(), "LMG limb kills should visibly sever one module")
	var fallback_corpse = CORPSE_SCENE.instantiate()
	add_child(fallback_corpse)
	fallback_corpse.setup(0.0, Vector2.RIGHT, 40.0, 2.25, "firearm_gib", "torso")
	_expect(fallback_corpse.attack_id == "shotgun" and fallback_corpse.dismemberment_state != "intact", "high-energy legacy death paths must not silently fall back to an intact pistol corpse")
	var blood_count_before_bag_test := get_tree().get_nodes_in_group("micro_blood_drop").size()
	corpse.apply_cleanup_tool("body_bag")
	corpse._spawn_blood_drop(corpse.global_position, 1.0, Vector2.RIGHT)
	await get_tree().process_frame
	_expect(corpse.is_bagged() and corpse.bleed_time == 0.0, "body bagging must seal the corpse immediately")
	_expect(get_tree().get_nodes_in_group("micro_blood_drop").size() == blood_count_before_bag_test, "bagged corpses must reject every later blood emission path")
	var drag_pixels_before := int(blood_system.ground_canvas.get_debug_pixel_count())
	blood_system.spawn_drag_smear(Vector2(80, 80), Vector2.RIGHT, 0.7)
	await get_tree().process_frame
	_expect(int(blood_system.ground_canvas.get_debug_pixel_count()) > drag_pixels_before, "dragging a bloody corpse should paint a continuous directional pixel smear")
	drop.queue_free()
	later_drop.queue_free()
	wall_stain.queue_free()
	if is_instance_valid(scrub_stain): scrub_stain.queue_free()
	line_stain.queue_free()
	residue_stain.queue_free()
	enemy.queue_free()
	corpse.queue_free()
	pistol_corpse.queue_free()
	lmg_corpse.queue_free()
	fallback_corpse.queue_free()
	blood_system.queue_free()
	await get_tree().process_frame
	CleanupRegistry.reset()
	if failures == 0:
		print("blood forensics regression: PASS")
		get_tree().quit(0)
	else: get_tree().quit(1)

func _expect(condition: bool, message: String) -> void:
	if condition: return
	failures += 1
	push_error(message)
