extends Node

func _ready() -> void:
	var a := TraumaCamera.new()
	var b := TraumaCamera.new()
	a.add_directional_impulse(Vector2.LEFT,4)
	b.add_directional_impulse(Vector2.LEFT,4)
	for i in 9: a.add_directional_impulse(Vector2.RIGHT,1)
	assert(a.directional_offset == Vector2(-4,0), "pellets/kill feedback cannot reverse or stack over heavy recoil")
	for i in 30: a.update_recoil(1.0/60.0)
	for i in 15: b.update_recoil(1.0/30.0)
	assert(a.directional_offset.distance_to(b.directional_offset) < 0.001, "recoil return is frame-rate independent")
	assert(a.directional_offset.x < 0 and a.directional_offset.length() < 0.05, "bounded return never overshoots")
	a.free()
	b.free()
	var camera := TraumaCamera.new()
	add_child(camera)
	camera.set_physics_process(false)
	camera._on_presented_weapon_fire(Vector2.ZERO,Vector2.RIGHT,false,"mossberg_590a1")
	assert(camera.directional_offset.x < -3, "shotgun kicks opposite firing axis")
	var offset := camera.directional_offset
	camera._on_presented_weapon_fire(Vector2.ZERO,Vector2.LEFT,true,"barrett_m82a1")
	assert(camera.directional_offset == offset, "enemy firing alone cannot shake player camera")
	camera.shake_strength = 0
	camera._physics_process(1.0/60.0)
	assert(camera.smooth_shake_offset == Vector2.ZERO)
	camera.free()
	var feedback := CombatFeedback.new()
	add_child(feedback)
	feedback.trigger_critical_hit_stop(true,false)
	var start := feedback.stop_history[0].x
	assert(feedback.trigger_finisher(true))
	assert(feedback.stop_history.size() == 1 and feedback.stop_history[0].y == 60)
	assert(feedback.hit_stop_deadline_msec == start+60 and Engine.time_scale == 0.0, "finish upgrades the same beat, not a second stop")
	assert(not feedback.trigger_finisher(true), "finish has a one-second cooldown")
	for i in 20: feedback.trigger_critical_hit_stop(true,true)
	assert(feedback.hit_stop_deadline_msec == start+60)
	while Time.get_ticks_msec() < start+90: await get_tree().process_frame
	assert(Engine.time_scale == 1.0 and not feedback.hit_stop_active)
	feedback.reset()
	feedback.stop_history = [Vector2i(Time.get_ticks_msec(),90)]
	feedback.trigger_finisher(false)
	assert(feedback.stop_history[-1].y == 10, "finish shares global 100ms budget")
	feedback.reset()
	feedback.trigger_finisher(true,0.0)
	assert(Engine.time_scale == 1.0, "hit-stop accessibility zero is respected")
	if DisplayServer.get_name() != "headless":
		var background := ColorRect.new()
		background.color = Color(0.2,0.2,0.2,1)
		add_child(background)
		background.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
		feedback.configure(background)
		feedback._set_finish_pulse(1.0)
		await RenderingServer.frame_post_draw
		var image := get_viewport().get_texture().get_image()
		var center := image.get_pixel(image.get_width()/2,image.get_height()/2)
		var edge := image.get_pixel(1,image.get_height()/2)
		assert(edge.r > center.r + 0.05 and is_equal_approx(edge.r,edge.g), "finish shader lights monochrome edges, not the gameplay center")
		image.save_png("/tmp/aftermath-finish-edge.png")
		feedback._set_finish_pulse(0.0)
		assert(not feedback.finish_edge.visible, "idle edge shader must not draw a full-screen pass")
	feedback.free()
	print("DIRECTIONAL_FINISH_FEEDBACK_OK")
	get_tree().quit()
